version: '3.8'

services:
  app:
    container_name: px-aissitent-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
    restart: always
    ports:
      - "${APP_PORT:-3000}:80"
    env_file:
      - .env
